blank_issues_enabled: false
contact_links:
  - name: Nuxt Community Discord
    url: https://discord.nuxtjs.org/
    about: Consider asking questions about the module here.
  - name: Documentation
    url: https://auth.nuxtjs.org/
    about: Check our documentation before reporting issues or questions.
